
#include <snekkja/schedule.h> 

#define TASK_NAME merge
#define TASK_ID 1
#include <snekkja.h>
#define DONE_merge1 1

size_t _snekkja_p;
size_t _snekkja_n;
size_t *_snekkja_tasks_in_core;
size_t *_snekkja_consumers_in_core;
size_t *_snekkja_producers_in_core;
snekkja_schedule_task_t **_snekkja_schedule;
size_t *_snekkja_tasks_in_core;
size_t *_snekkja_consumers_in_core;
size_t *_snekkja_producers_in_core;
size_t *_snekkja_consumers_in_task;
size_t *_snekkja_producers_in_task;
size_t *_snekkja_remote_consumers_in_task;
size_t *_snekkja_remote_producers_in_task;
size_t **_snekkja_consumers_id;
size_t **_snekkja_producers_id;

void snekkja_schedule_init()
{
	_snekkja_p = 6;
	_snekkja_n = 128;

	_snekkja_tasks_in_core = malloc(sizeof(size_t) * _snekkja_p);
	_snekkja_tasks_in_core[0] = 1;
	_snekkja_tasks_in_core[1] = 2;
	_snekkja_tasks_in_core[2] = 4;
	_snekkja_tasks_in_core[3] = 8;
	_snekkja_tasks_in_core[4] = 16;
	_snekkja_tasks_in_core[5] = 32;

	_snekkja_consumers_in_core = malloc(sizeof(size_t) * _snekkja_p);
	_snekkja_consumers_in_core[0] = 0;
	_snekkja_consumers_in_core[1] = 2;
	_snekkja_consumers_in_core[2] = 4;
	_snekkja_consumers_in_core[3] = 8;
	_snekkja_consumers_in_core[4] = 16;
	_snekkja_consumers_in_core[5] = 32;

	_snekkja_producers_in_core = malloc(sizeof(size_t) * _snekkja_p);
	_snekkja_producers_in_core[0] = 2;
	_snekkja_producers_in_core[1] = 4;
	_snekkja_producers_in_core[2] = 8;
	_snekkja_producers_in_core[3] = 16;
	_snekkja_producers_in_core[4] = 32;
	_snekkja_producers_in_core[5] = 0;

	_snekkja_consumers_in_task = malloc(sizeof(size_t) * _snekkja_n);
	_snekkja_consumers_in_task[0] = 0;
	_snekkja_consumers_in_task[1] = 0;
	_snekkja_consumers_in_task[2] = 0;
	_snekkja_consumers_in_task[3] = 0;
	_snekkja_consumers_in_task[4] = 1;
	_snekkja_consumers_in_task[5] = 1;
	_snekkja_consumers_in_task[6] = 0;
	_snekkja_consumers_in_task[7] = 0;
	_snekkja_consumers_in_task[8] = 1;
	_snekkja_consumers_in_task[9] = 1;
	_snekkja_consumers_in_task[10] = 1;
	_snekkja_consumers_in_task[11] = 1;
	_snekkja_consumers_in_task[12] = 0;
	_snekkja_consumers_in_task[13] = 0;
	_snekkja_consumers_in_task[14] = 0;
	_snekkja_consumers_in_task[15] = 0;
	_snekkja_consumers_in_task[16] = 1;
	_snekkja_consumers_in_task[17] = 1;
	_snekkja_consumers_in_task[18] = 1;
	_snekkja_consumers_in_task[19] = 1;
	_snekkja_consumers_in_task[20] = 1;
	_snekkja_consumers_in_task[21] = 1;
	_snekkja_consumers_in_task[22] = 1;
	_snekkja_consumers_in_task[23] = 1;
	_snekkja_consumers_in_task[24] = 0;
	_snekkja_consumers_in_task[25] = 0;
	_snekkja_consumers_in_task[26] = 0;
	_snekkja_consumers_in_task[27] = 0;
	_snekkja_consumers_in_task[28] = 0;
	_snekkja_consumers_in_task[29] = 0;
	_snekkja_consumers_in_task[30] = 0;
	_snekkja_consumers_in_task[31] = 0;
	_snekkja_consumers_in_task[32] = 1;
	_snekkja_consumers_in_task[33] = 1;
	_snekkja_consumers_in_task[34] = 1;
	_snekkja_consumers_in_task[35] = 1;
	_snekkja_consumers_in_task[36] = 1;
	_snekkja_consumers_in_task[37] = 1;
	_snekkja_consumers_in_task[38] = 1;
	_snekkja_consumers_in_task[39] = 1;
	_snekkja_consumers_in_task[40] = 1;
	_snekkja_consumers_in_task[41] = 1;
	_snekkja_consumers_in_task[42] = 1;
	_snekkja_consumers_in_task[43] = 1;
	_snekkja_consumers_in_task[44] = 1;
	_snekkja_consumers_in_task[45] = 1;
	_snekkja_consumers_in_task[46] = 1;
	_snekkja_consumers_in_task[47] = 1;
	_snekkja_consumers_in_task[48] = 0;
	_snekkja_consumers_in_task[49] = 0;
	_snekkja_consumers_in_task[50] = 0;
	_snekkja_consumers_in_task[51] = 0;
	_snekkja_consumers_in_task[52] = 0;
	_snekkja_consumers_in_task[53] = 0;
	_snekkja_consumers_in_task[54] = 0;
	_snekkja_consumers_in_task[55] = 0;
	_snekkja_consumers_in_task[56] = 0;
	_snekkja_consumers_in_task[67] = 0;
	_snekkja_consumers_in_task[58] = 0;
	_snekkja_consumers_in_task[59] = 0;
	_snekkja_consumers_in_task[60] = 0;
	_snekkja_consumers_in_task[61] = 0;
	_snekkja_consumers_in_task[62] = 0;
	_snekkja_consumers_in_task[63] = 0;
	_snekkja_consumers_in_task[64] = 1;
	_snekkja_consumers_in_task[65] = 1;
	_snekkja_consumers_in_task[66] = 1;
	_snekkja_consumers_in_task[67] = 1;
	_snekkja_consumers_in_task[68] = 1;
	_snekkja_consumers_in_task[69] = 1;
	_snekkja_consumers_in_task[70] = 1;
	_snekkja_consumers_in_task[71] = 1;
	_snekkja_consumers_in_task[72] = 1;
	_snekkja_consumers_in_task[73] = 1;
	_snekkja_consumers_in_task[74] = 1;
	_snekkja_consumers_in_task[75] = 1;
	_snekkja_consumers_in_task[76] = 1;
	_snekkja_consumers_in_task[77] = 1;
	_snekkja_consumers_in_task[78] = 1;
	_snekkja_consumers_in_task[79] = 1;
	_snekkja_consumers_in_task[80] = 1;
	_snekkja_consumers_in_task[81] = 1;
	_snekkja_consumers_in_task[82] = 1;
	_snekkja_consumers_in_task[83] = 1;
	_snekkja_consumers_in_task[84] = 1;
	_snekkja_consumers_in_task[85] = 1;
	_snekkja_consumers_in_task[86] = 1;
	_snekkja_consumers_in_task[87] = 1;
	_snekkja_consumers_in_task[88] = 1;
	_snekkja_consumers_in_task[89] = 1;
	_snekkja_consumers_in_task[90] = 1;
	_snekkja_consumers_in_task[91] = 1;
	_snekkja_consumers_in_task[92] = 1;
	_snekkja_consumers_in_task[93] = 1;
	_snekkja_consumers_in_task[94] = 1;
	_snekkja_consumers_in_task[95] = 1;
	_snekkja_consumers_in_task[96] = 0;
	_snekkja_consumers_in_task[97] = 0;
	_snekkja_consumers_in_task[98] = 0;
	_snekkja_consumers_in_task[99] = 0;
	_snekkja_consumers_in_task[100] = 0;
	_snekkja_consumers_in_task[101] = 0;
	_snekkja_consumers_in_task[102] = 0;
	_snekkja_consumers_in_task[103] = 0;
	_snekkja_consumers_in_task[104] = 0;
	_snekkja_consumers_in_task[105] = 0;
	_snekkja_consumers_in_task[106] = 0;
	_snekkja_consumers_in_task[107] = 0;
	_snekkja_consumers_in_task[108] = 0;
	_snekkja_consumers_in_task[109] = 0;
	_snekkja_consumers_in_task[110] = 0;
	_snekkja_consumers_in_task[111] = 0;
	_snekkja_consumers_in_task[112] = 0;
	_snekkja_consumers_in_task[113] = 0;
	_snekkja_consumers_in_task[114] = 0;
	_snekkja_consumers_in_task[115] = 0;
	_snekkja_consumers_in_task[116] = 0;
	_snekkja_consumers_in_task[117] = 0;
	_snekkja_consumers_in_task[118] = 0;
	_snekkja_consumers_in_task[119] = 0;
	_snekkja_consumers_in_task[120] = 0;
	_snekkja_consumers_in_task[121] = 0;
	_snekkja_consumers_in_task[122] = 0;
	_snekkja_consumers_in_task[123] = 0;
	_snekkja_consumers_in_task[124] = 0;
	_snekkja_consumers_in_task[125] = 0;
	_snekkja_consumers_in_task[126] = 0;
	_snekkja_consumers_in_task[127] = 0;

	_snekkja_producers_in_task = malloc(sizeof(size_t) * _snekkja_n);
	_snekkja_producers_in_task[0] = 0;
	_snekkja_producers_in_task[1] = 0;
	_snekkja_producers_in_task[2] = 2;
	_snekkja_producers_in_task[3] = 0;
	_snekkja_producers_in_task[4] = 2;
	_snekkja_producers_in_task[5] = 2;
	_snekkja_producers_in_task[6] = 0;
	_snekkja_producers_in_task[7] = 0;
	_snekkja_producers_in_task[8] = 2;
	_snekkja_producers_in_task[9] = 2;
	_snekkja_producers_in_task[10] = 2;
	_snekkja_producers_in_task[11] = 2;
	_snekkja_producers_in_task[12] = 0;
	_snekkja_producers_in_task[13] = 0;
	_snekkja_producers_in_task[14] = 0;
	_snekkja_producers_in_task[15] = 0;
	_snekkja_producers_in_task[16] = 2;
	_snekkja_producers_in_task[17] = 2;
	_snekkja_producers_in_task[18] = 2;
	_snekkja_producers_in_task[19] = 2;
	_snekkja_producers_in_task[20] = 2;
	_snekkja_producers_in_task[21] = 2;
	_snekkja_producers_in_task[22] = 2;
	_snekkja_producers_in_task[23] = 2;
	_snekkja_producers_in_task[24] = 0;
	_snekkja_producers_in_task[25] = 0;
	_snekkja_producers_in_task[26] = 0;
	_snekkja_producers_in_task[27] = 0;
	_snekkja_producers_in_task[28] = 0;
	_snekkja_producers_in_task[29] = 0;
	_snekkja_producers_in_task[30] = 0;
	_snekkja_producers_in_task[31] = 0;
	_snekkja_producers_in_task[32] = 2;
	_snekkja_producers_in_task[33] = 2;
	_snekkja_producers_in_task[34] = 2;
	_snekkja_producers_in_task[35] = 2;
	_snekkja_producers_in_task[36] = 2;
	_snekkja_producers_in_task[37] = 2;
	_snekkja_producers_in_task[38] = 2;
	_snekkja_producers_in_task[39] = 2;
	_snekkja_producers_in_task[40] = 2;
	_snekkja_producers_in_task[41] = 2;
	_snekkja_producers_in_task[42] = 2;
	_snekkja_producers_in_task[43] = 2;
	_snekkja_producers_in_task[44] = 2;
	_snekkja_producers_in_task[45] = 2;
	_snekkja_producers_in_task[46] = 2;
	_snekkja_producers_in_task[47] = 2;
	_snekkja_producers_in_task[48] = 0;
	_snekkja_producers_in_task[49] = 0;
	_snekkja_producers_in_task[50] = 0;
	_snekkja_producers_in_task[51] = 0;
	_snekkja_producers_in_task[52] = 0;
	_snekkja_producers_in_task[53] = 0;
	_snekkja_producers_in_task[54] = 0;
	_snekkja_producers_in_task[55] = 0;
	_snekkja_producers_in_task[56] = 0;
	_snekkja_producers_in_task[57] = 0;
	_snekkja_producers_in_task[58] = 0;
	_snekkja_producers_in_task[59] = 0;
	_snekkja_producers_in_task[60] = 0;
	_snekkja_producers_in_task[61] = 0;
	_snekkja_producers_in_task[62] = 0;
	_snekkja_producers_in_task[63] = 0;
	_snekkja_producers_in_task[64] = 0;
	_snekkja_producers_in_task[65] = 0;
	_snekkja_producers_in_task[66] = 0;
	_snekkja_producers_in_task[67] = 0;
	_snekkja_producers_in_task[68] = 0;
	_snekkja_producers_in_task[69] = 0;
	_snekkja_producers_in_task[70] = 0;
	_snekkja_producers_in_task[71] = 0;
	_snekkja_producers_in_task[72] = 0;
	_snekkja_producers_in_task[73] = 0;
	_snekkja_producers_in_task[74] = 0;
	_snekkja_producers_in_task[75] = 0;
	_snekkja_producers_in_task[76] = 0;
	_snekkja_producers_in_task[77] = 0;
	_snekkja_producers_in_task[78] = 0;
	_snekkja_producers_in_task[79] = 0;
	_snekkja_producers_in_task[80] = 0;
	_snekkja_producers_in_task[81] = 0;
	_snekkja_producers_in_task[82] = 0;
	_snekkja_producers_in_task[83] = 0;
	_snekkja_producers_in_task[84] = 0;
	_snekkja_producers_in_task[85] = 0;
	_snekkja_producers_in_task[86] = 0;
	_snekkja_producers_in_task[87] = 0;
	_snekkja_producers_in_task[88] = 0;
	_snekkja_producers_in_task[89] = 0;
	_snekkja_producers_in_task[90] = 0;
	_snekkja_producers_in_task[91] = 0;
	_snekkja_producers_in_task[92] = 0;
	_snekkja_producers_in_task[93] = 0;
	_snekkja_producers_in_task[94] = 0;
	_snekkja_producers_in_task[95] = 0;
	_snekkja_producers_in_task[96] = 0;
	_snekkja_producers_in_task[97] = 0;
	_snekkja_producers_in_task[98] = 0;
	_snekkja_producers_in_task[99] = 0;
	_snekkja_producers_in_task[100] = 0;
	_snekkja_producers_in_task[101] = 0;
	_snekkja_producers_in_task[102] = 0;
	_snekkja_producers_in_task[103] = 0;
	_snekkja_producers_in_task[104] = 0;
	_snekkja_producers_in_task[105] = 0;
	_snekkja_producers_in_task[106] = 0;
	_snekkja_producers_in_task[107] = 0;
	_snekkja_producers_in_task[108] = 0;
	_snekkja_producers_in_task[109] = 0;
	_snekkja_producers_in_task[110] = 0;
	_snekkja_producers_in_task[111] = 0;
	_snekkja_producers_in_task[112] = 0;
	_snekkja_producers_in_task[113] = 0;
	_snekkja_producers_in_task[114] = 0;
	_snekkja_producers_in_task[115] = 0;
	_snekkja_producers_in_task[116] = 0;
	_snekkja_producers_in_task[117] = 0;
	_snekkja_producers_in_task[118] = 0;
	_snekkja_producers_in_task[119] = 0;
	_snekkja_producers_in_task[120] = 0;
	_snekkja_producers_in_task[121] = 0;
	_snekkja_producers_in_task[122] = 0;
	_snekkja_producers_in_task[123] = 0;
	_snekkja_producers_in_task[124] = 0;
	_snekkja_producers_in_task[125] = 0;
	_snekkja_producers_in_task[126] = 0;
	_snekkja_producers_in_task[127] = 0;

	_snekkja_remote_consumers_in_task = malloc(sizeof(size_t) * _snekkja_n);
	_snekkja_remote_consumers_in_task[0] = 0;
	_snekkja_remote_consumers_in_task[1] = 0;
	_snekkja_remote_consumers_in_task[2] = 0;
	_snekkja_remote_consumers_in_task[3] = 0;
	_snekkja_remote_consumers_in_task[4] = 1;
	_snekkja_remote_consumers_in_task[5] = 1;
	_snekkja_remote_consumers_in_task[6] = 0;
	_snekkja_remote_consumers_in_task[7] = 0;
	_snekkja_remote_consumers_in_task[8] = 1;
	_snekkja_remote_consumers_in_task[9] = 1;
	_snekkja_remote_consumers_in_task[10] = 1;
	_snekkja_remote_consumers_in_task[11] = 1;
	_snekkja_remote_consumers_in_task[12] = 0;
	_snekkja_remote_consumers_in_task[13] = 0;
	_snekkja_remote_consumers_in_task[14] = 0;
	_snekkja_remote_consumers_in_task[15] = 0;
	_snekkja_remote_consumers_in_task[16] = 1;
	_snekkja_remote_consumers_in_task[17] = 1;
	_snekkja_remote_consumers_in_task[18] = 1;
	_snekkja_remote_consumers_in_task[19] = 1;
	_snekkja_remote_consumers_in_task[20] = 1;
	_snekkja_remote_consumers_in_task[21] = 1;
	_snekkja_remote_consumers_in_task[22] = 1;
	_snekkja_remote_consumers_in_task[23] = 1;
	_snekkja_remote_consumers_in_task[24] = 0;
	_snekkja_remote_consumers_in_task[25] = 0;
	_snekkja_remote_consumers_in_task[26] = 0;
	_snekkja_remote_consumers_in_task[27] = 0;
	_snekkja_remote_consumers_in_task[28] = 0;
	_snekkja_remote_consumers_in_task[29] = 0;
	_snekkja_remote_consumers_in_task[30] = 0;
	_snekkja_remote_consumers_in_task[31] = 0;
	_snekkja_remote_consumers_in_task[32] = 1;
	_snekkja_remote_consumers_in_task[33] = 1;
	_snekkja_remote_consumers_in_task[34] = 1;
	_snekkja_remote_consumers_in_task[35] = 1;
	_snekkja_remote_consumers_in_task[36] = 1;
	_snekkja_remote_consumers_in_task[37] = 1;
	_snekkja_remote_consumers_in_task[38] = 1;
	_snekkja_remote_consumers_in_task[39] = 1;
	_snekkja_remote_consumers_in_task[40] = 1;
	_snekkja_remote_consumers_in_task[41] = 1;
	_snekkja_remote_consumers_in_task[42] = 1;
	_snekkja_remote_consumers_in_task[43] = 1;
	_snekkja_remote_consumers_in_task[44] = 1;
	_snekkja_remote_consumers_in_task[45] = 1;
	_snekkja_remote_consumers_in_task[46] = 1;
	_snekkja_remote_consumers_in_task[47] = 1;
	_snekkja_remote_consumers_in_task[48] = 0;
	_snekkja_remote_consumers_in_task[49] = 0;
	_snekkja_remote_consumers_in_task[50] = 0;
	_snekkja_remote_consumers_in_task[51] = 0;
	_snekkja_remote_consumers_in_task[52] = 0;
	_snekkja_remote_consumers_in_task[53] = 0;
	_snekkja_remote_consumers_in_task[54] = 0;
	_snekkja_remote_consumers_in_task[55] = 0;
	_snekkja_remote_consumers_in_task[56] = 0;
	_snekkja_remote_consumers_in_task[67] = 0;
	_snekkja_remote_consumers_in_task[58] = 0;
	_snekkja_remote_consumers_in_task[59] = 0;
	_snekkja_remote_consumers_in_task[60] = 0;
	_snekkja_remote_consumers_in_task[61] = 0;
	_snekkja_remote_consumers_in_task[62] = 0;
	_snekkja_remote_consumers_in_task[63] = 0;
	_snekkja_remote_consumers_in_task[64] = 1;
	_snekkja_remote_consumers_in_task[65] = 1;
	_snekkja_remote_consumers_in_task[66] = 1;
	_snekkja_remote_consumers_in_task[67] = 1;
	_snekkja_remote_consumers_in_task[68] = 1;
	_snekkja_remote_consumers_in_task[69] = 1;
	_snekkja_remote_consumers_in_task[70] = 1;
	_snekkja_remote_consumers_in_task[71] = 1;
	_snekkja_remote_consumers_in_task[72] = 1;
	_snekkja_remote_consumers_in_task[73] = 1;
	_snekkja_remote_consumers_in_task[74] = 1;
	_snekkja_remote_consumers_in_task[75] = 1;
	_snekkja_remote_consumers_in_task[76] = 1;
	_snekkja_remote_consumers_in_task[77] = 1;
	_snekkja_remote_consumers_in_task[78] = 1;
	_snekkja_remote_consumers_in_task[79] = 1;
	_snekkja_remote_consumers_in_task[80] = 1;
	_snekkja_remote_consumers_in_task[81] = 1;
	_snekkja_remote_consumers_in_task[82] = 1;
	_snekkja_remote_consumers_in_task[83] = 1;
	_snekkja_remote_consumers_in_task[84] = 1;
	_snekkja_remote_consumers_in_task[85] = 1;
	_snekkja_remote_consumers_in_task[86] = 1;
	_snekkja_remote_consumers_in_task[87] = 1;
	_snekkja_remote_consumers_in_task[88] = 1;
	_snekkja_remote_consumers_in_task[89] = 1;
	_snekkja_remote_consumers_in_task[90] = 1;
	_snekkja_remote_consumers_in_task[91] = 1;
	_snekkja_remote_consumers_in_task[92] = 1;
	_snekkja_remote_consumers_in_task[93] = 1;
	_snekkja_remote_consumers_in_task[94] = 1;
	_snekkja_remote_consumers_in_task[95] = 1;
	_snekkja_remote_consumers_in_task[96] = 0;
	_snekkja_remote_consumers_in_task[97] = 0;
	_snekkja_remote_consumers_in_task[98] = 0;
	_snekkja_remote_consumers_in_task[99] = 0;
	_snekkja_remote_consumers_in_task[100] = 0;
	_snekkja_remote_consumers_in_task[101] = 0;
	_snekkja_remote_consumers_in_task[102] = 0;
	_snekkja_remote_consumers_in_task[103] = 0;
	_snekkja_remote_consumers_in_task[104] = 0;
	_snekkja_remote_consumers_in_task[105] = 0;
	_snekkja_remote_consumers_in_task[106] = 0;
	_snekkja_remote_consumers_in_task[107] = 0;
	_snekkja_remote_consumers_in_task[108] = 0;
	_snekkja_remote_consumers_in_task[109] = 0;
	_snekkja_remote_consumers_in_task[110] = 0;
	_snekkja_remote_consumers_in_task[111] = 0;
	_snekkja_remote_consumers_in_task[112] = 0;
	_snekkja_remote_consumers_in_task[113] = 0;
	_snekkja_remote_consumers_in_task[114] = 0;
	_snekkja_remote_consumers_in_task[115] = 0;
	_snekkja_remote_consumers_in_task[116] = 0;
	_snekkja_remote_consumers_in_task[117] = 0;
	_snekkja_remote_consumers_in_task[118] = 0;
	_snekkja_remote_consumers_in_task[119] = 0;
	_snekkja_remote_consumers_in_task[120] = 0;
	_snekkja_remote_consumers_in_task[121] = 0;
	_snekkja_remote_consumers_in_task[122] = 0;
	_snekkja_remote_consumers_in_task[123] = 0;
	_snekkja_remote_consumers_in_task[124] = 0;
	_snekkja_remote_consumers_in_task[125] = 0;
	_snekkja_remote_consumers_in_task[126] = 0;
	_snekkja_remote_consumers_in_task[127] = 0;

	_snekkja_remote_producers_in_task = malloc(sizeof(size_t) * _snekkja_n);
	_snekkja_remote_producers_in_task[0] = 0;
	_snekkja_remote_producers_in_task[1] = 0;
	_snekkja_remote_producers_in_task[2] = 2;
	_snekkja_remote_producers_in_task[3] = 0;
	_snekkja_remote_producers_in_task[4] = 2;
	_snekkja_remote_producers_in_task[5] = 2;
	_snekkja_remote_producers_in_task[6] = 0;
	_snekkja_remote_producers_in_task[7] = 0;
	_snekkja_remote_producers_in_task[8] = 2;
	_snekkja_remote_producers_in_task[9] = 2;
	_snekkja_remote_producers_in_task[10] = 2;
	_snekkja_remote_producers_in_task[11] = 2;
	_snekkja_remote_producers_in_task[12] = 0;
	_snekkja_remote_producers_in_task[13] = 0;
	_snekkja_remote_producers_in_task[14] = 0;
	_snekkja_remote_producers_in_task[15] = 0;
	_snekkja_remote_producers_in_task[16] = 2;
	_snekkja_remote_producers_in_task[17] = 2;
	_snekkja_remote_producers_in_task[18] = 2;
	_snekkja_remote_producers_in_task[19] = 2;
	_snekkja_remote_producers_in_task[20] = 2;
	_snekkja_remote_producers_in_task[21] = 2;
	_snekkja_remote_producers_in_task[22] = 2;
	_snekkja_remote_producers_in_task[23] = 2;
	_snekkja_remote_producers_in_task[24] = 0;
	_snekkja_remote_producers_in_task[25] = 0;
	_snekkja_remote_producers_in_task[26] = 0;
	_snekkja_remote_producers_in_task[27] = 0;
	_snekkja_remote_producers_in_task[28] = 0;
	_snekkja_remote_producers_in_task[29] = 0;
	_snekkja_remote_producers_in_task[30] = 0;
	_snekkja_remote_producers_in_task[31] = 0;
	_snekkja_remote_producers_in_task[32] = 2;
	_snekkja_remote_producers_in_task[33] = 2;
	_snekkja_remote_producers_in_task[34] = 2;
	_snekkja_remote_producers_in_task[35] = 2;
	_snekkja_remote_producers_in_task[36] = 2;
	_snekkja_remote_producers_in_task[37] = 2;
	_snekkja_remote_producers_in_task[38] = 2;
	_snekkja_remote_producers_in_task[39] = 2;
	_snekkja_remote_producers_in_task[40] = 2;
	_snekkja_remote_producers_in_task[41] = 2;
	_snekkja_remote_producers_in_task[42] = 2;
	_snekkja_remote_producers_in_task[43] = 2;
	_snekkja_remote_producers_in_task[44] = 2;
	_snekkja_remote_producers_in_task[45] = 2;
	_snekkja_remote_producers_in_task[46] = 2;
	_snekkja_remote_producers_in_task[47] = 2;
	_snekkja_remote_producers_in_task[48] = 0;
	_snekkja_remote_producers_in_task[49] = 0;
	_snekkja_remote_producers_in_task[50] = 0;
	_snekkja_remote_producers_in_task[51] = 0;
	_snekkja_remote_producers_in_task[52] = 0;
	_snekkja_remote_producers_in_task[53] = 0;
	_snekkja_remote_producers_in_task[54] = 0;
	_snekkja_remote_producers_in_task[55] = 0;
	_snekkja_remote_producers_in_task[56] = 0;
	_snekkja_remote_producers_in_task[57] = 0;
	_snekkja_remote_producers_in_task[58] = 0;
	_snekkja_remote_producers_in_task[59] = 0;
	_snekkja_remote_producers_in_task[60] = 0;
	_snekkja_remote_producers_in_task[61] = 0;
	_snekkja_remote_producers_in_task[62] = 0;
	_snekkja_remote_producers_in_task[63] = 0;
	_snekkja_remote_producers_in_task[64] = 0;
	_snekkja_remote_producers_in_task[65] = 0;
	_snekkja_remote_producers_in_task[66] = 0;
	_snekkja_remote_producers_in_task[67] = 0;
	_snekkja_remote_producers_in_task[68] = 0;
	_snekkja_remote_producers_in_task[69] = 0;
	_snekkja_remote_producers_in_task[70] = 0;
	_snekkja_remote_producers_in_task[71] = 0;
	_snekkja_remote_producers_in_task[72] = 0;
	_snekkja_remote_producers_in_task[73] = 0;
	_snekkja_remote_producers_in_task[74] = 0;
	_snekkja_remote_producers_in_task[75] = 0;
	_snekkja_remote_producers_in_task[76] = 0;
	_snekkja_remote_producers_in_task[77] = 0;
	_snekkja_remote_producers_in_task[78] = 0;
	_snekkja_remote_producers_in_task[79] = 0;
	_snekkja_remote_producers_in_task[80] = 0;
	_snekkja_remote_producers_in_task[81] = 0;
	_snekkja_remote_producers_in_task[82] = 0;
	_snekkja_remote_producers_in_task[83] = 0;
	_snekkja_remote_producers_in_task[84] = 0;
	_snekkja_remote_producers_in_task[85] = 0;
	_snekkja_remote_producers_in_task[86] = 0;
	_snekkja_remote_producers_in_task[87] = 0;
	_snekkja_remote_producers_in_task[88] = 0;
	_snekkja_remote_producers_in_task[89] = 0;
	_snekkja_remote_producers_in_task[90] = 0;
	_snekkja_remote_producers_in_task[91] = 0;
	_snekkja_remote_producers_in_task[92] = 0;
	_snekkja_remote_producers_in_task[93] = 0;
	_snekkja_remote_producers_in_task[94] = 0;
	_snekkja_remote_producers_in_task[95] = 0;
	_snekkja_remote_producers_in_task[96] = 0;
	_snekkja_remote_producers_in_task[97] = 0;
	_snekkja_remote_producers_in_task[98] = 0;
	_snekkja_remote_producers_in_task[99] = 0;
	_snekkja_remote_producers_in_task[100] = 0;
	_snekkja_remote_producers_in_task[101] = 0;
	_snekkja_remote_producers_in_task[102] = 0;
	_snekkja_remote_producers_in_task[103] = 0;
	_snekkja_remote_producers_in_task[104] = 0;
	_snekkja_remote_producers_in_task[105] = 0;
	_snekkja_remote_producers_in_task[106] = 0;
	_snekkja_remote_producers_in_task[107] = 0;
	_snekkja_remote_producers_in_task[108] = 0;
	_snekkja_remote_producers_in_task[109] = 0;
	_snekkja_remote_producers_in_task[110] = 0;
	_snekkja_remote_producers_in_task[111] = 0;
	_snekkja_remote_producers_in_task[112] = 0;
	_snekkja_remote_producers_in_task[113] = 0;
	_snekkja_remote_producers_in_task[114] = 0;
	_snekkja_remote_producers_in_task[115] = 0;
	_snekkja_remote_producers_in_task[116] = 0;
	_snekkja_remote_producers_in_task[117] = 0;
	_snekkja_remote_producers_in_task[118] = 0;
	_snekkja_remote_producers_in_task[119] = 0;
	_snekkja_remote_producers_in_task[120] = 0;
	_snekkja_remote_producers_in_task[121] = 0;
	_snekkja_remote_producers_in_task[122] = 0;
	_snekkja_remote_producers_in_task[123] = 0;
	_snekkja_remote_producers_in_task[124] = 0;
	_snekkja_remote_producers_in_task[125] = 0;
	_snekkja_remote_producers_in_task[126] = 0;
	_snekkja_remote_producers_in_task[127] = 0;

	_snekkja_producers_id = malloc(sizeof(size_t*) * _snekkja_n);
	_snekkja_producers_id[0] = NULL;
	_snekkja_producers_id[1] = NULL;
	_snekkja_producers_id[2] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[2][0] = 5;
	_snekkja_producers_id[2][1] = 6;
	_snekkja_producers_id[3] = NULL;
	_snekkja_producers_id[4] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[4][0] = 9;
	_snekkja_producers_id[4][1] = 10;
	_snekkja_producers_id[5] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[5][0] = 11;
	_snekkja_producers_id[5][1] = 12;
	_snekkja_producers_id[6] = NULL;
	_snekkja_producers_id[7] = NULL;
	_snekkja_producers_id[8] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[8][0] = 17;
	_snekkja_producers_id[8][1] = 18;
	_snekkja_producers_id[9] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[9][0] = 19;
	_snekkja_producers_id[9][1] = 20;
	_snekkja_producers_id[10] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[10][0] = 21;
	_snekkja_producers_id[10][1] = 22;
	_snekkja_producers_id[11] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[11][0] = 23;
	_snekkja_producers_id[11][1] = 24;
	_snekkja_producers_id[12] = NULL;
	_snekkja_producers_id[13] = NULL;
	_snekkja_producers_id[14] = NULL;
	_snekkja_producers_id[15] = NULL;
	_snekkja_producers_id[16] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[16][0] = 33;
	_snekkja_producers_id[16][1] = 34;
	_snekkja_producers_id[17] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[17][0] = 35;
	_snekkja_producers_id[17][1] = 36;
	_snekkja_producers_id[18] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[18][0] = 37;
	_snekkja_producers_id[18][1] = 38;
	_snekkja_producers_id[19] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[19][0] = 39;
	_snekkja_producers_id[19][1] = 40;
	_snekkja_producers_id[20] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[20][0] = 41;
	_snekkja_producers_id[20][1] = 42;
	_snekkja_producers_id[21] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[21][0] = 43;
	_snekkja_producers_id[21][1] = 44;
	_snekkja_producers_id[22] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[22][0] = 45;
	_snekkja_producers_id[22][1] = 46;
	_snekkja_producers_id[23] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[23][0] = 47;
	_snekkja_producers_id[23][1] = 48;
	_snekkja_producers_id[24] = NULL;
	_snekkja_producers_id[25] = NULL;
	_snekkja_producers_id[26] = NULL;
	_snekkja_producers_id[27] = NULL;
	_snekkja_producers_id[28] = NULL;
	_snekkja_producers_id[29] = NULL;
	_snekkja_producers_id[30] = NULL;
	_snekkja_producers_id[31] = NULL;
	_snekkja_producers_id[32] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[32][0] = 65;
	_snekkja_producers_id[32][1] = 66;
	_snekkja_producers_id[33] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[33][0] = 67;
	_snekkja_producers_id[33][1] = 68;
	_snekkja_producers_id[34] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[34][0] = 69;
	_snekkja_producers_id[34][1] = 70;
	_snekkja_producers_id[35] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[35][0] = 71;
	_snekkja_producers_id[35][1] = 72;
	_snekkja_producers_id[36] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[36][0] = 73;
	_snekkja_producers_id[36][1] = 74;
	_snekkja_producers_id[37] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[37][0] = 75;
	_snekkja_producers_id[37][1] = 76;
	_snekkja_producers_id[38] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[38][0] = 77;
	_snekkja_producers_id[38][1] = 78;
	_snekkja_producers_id[39] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[39][0] = 79;
	_snekkja_producers_id[39][1] = 80;
	_snekkja_producers_id[40] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[40][0] = 81;
	_snekkja_producers_id[40][1] = 82;
	_snekkja_producers_id[41] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[41][0] = 83;
	_snekkja_producers_id[41][1] = 84;
	_snekkja_producers_id[42] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[42][0] = 85;
	_snekkja_producers_id[42][1] = 86;
	_snekkja_producers_id[43] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[43][0] = 87;
	_snekkja_producers_id[43][1] = 88;
	_snekkja_producers_id[44] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[44][0] = 89;
	_snekkja_producers_id[44][1] = 90;
	_snekkja_producers_id[45] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[45][0] = 91;
	_snekkja_producers_id[45][1] = 92;
	_snekkja_producers_id[46] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[46][0] = 93;
	_snekkja_producers_id[46][1] = 94;
	_snekkja_producers_id[47] = malloc(sizeof(size_t) * 2);
	_snekkja_producers_id[47][0] = 95;
	_snekkja_producers_id[47][1] = 96;
	_snekkja_producers_id[48] = NULL;
	_snekkja_producers_id[49] = NULL;
	_snekkja_producers_id[50] = NULL;
	_snekkja_producers_id[51] = NULL;
	_snekkja_producers_id[52] = NULL;
	_snekkja_producers_id[53] = NULL;
	_snekkja_producers_id[54] = NULL;
	_snekkja_producers_id[55] = NULL;
	_snekkja_producers_id[56] = NULL;
	_snekkja_producers_id[57] = NULL;
	_snekkja_producers_id[58] = NULL;
	_snekkja_producers_id[59] = NULL;
	_snekkja_producers_id[60] = NULL;
	_snekkja_producers_id[61] = NULL;
	_snekkja_producers_id[62] = NULL;
	_snekkja_producers_id[63] = NULL;
	_snekkja_producers_id[64] = NULL;
	_snekkja_producers_id[65] = NULL;
	_snekkja_producers_id[66] = NULL;
	_snekkja_producers_id[67] = NULL;
	_snekkja_producers_id[68] = NULL;
	_snekkja_producers_id[69] = NULL;
	_snekkja_producers_id[70] = NULL;
	_snekkja_producers_id[71] = NULL;
	_snekkja_producers_id[72] = NULL;
	_snekkja_producers_id[73] = NULL;
	_snekkja_producers_id[74] = NULL;
	_snekkja_producers_id[75] = NULL;
	_snekkja_producers_id[76] = NULL;
	_snekkja_producers_id[77] = NULL;
	_snekkja_producers_id[78] = NULL;
	_snekkja_producers_id[79] = NULL;
	_snekkja_producers_id[80] = NULL;
	_snekkja_producers_id[81] = NULL;
	_snekkja_producers_id[82] = NULL;
	_snekkja_producers_id[83] = NULL;
	_snekkja_producers_id[84] = NULL;
	_snekkja_producers_id[85] = NULL;
	_snekkja_producers_id[86] = NULL;
	_snekkja_producers_id[87] = NULL;
	_snekkja_producers_id[88] = NULL;
	_snekkja_producers_id[89] = NULL;
	_snekkja_producers_id[90] = NULL;
	_snekkja_producers_id[91] = NULL;
	_snekkja_producers_id[92] = NULL;
	_snekkja_producers_id[93] = NULL;
	_snekkja_producers_id[94] = NULL;
	_snekkja_producers_id[95] = NULL;
	_snekkja_producers_id[96] = NULL;
	_snekkja_producers_id[97] = NULL;
	_snekkja_producers_id[98] = NULL;
	_snekkja_producers_id[99] = NULL;
	_snekkja_producers_id[100] = NULL;
	_snekkja_producers_id[101] = NULL;
	_snekkja_producers_id[102] = NULL;
	_snekkja_producers_id[103] = NULL;
	_snekkja_producers_id[104] = NULL;
	_snekkja_producers_id[105] = NULL;
	_snekkja_producers_id[106] = NULL;
	_snekkja_producers_id[107] = NULL;
	_snekkja_producers_id[108] = NULL;
	_snekkja_producers_id[109] = NULL;
	_snekkja_producers_id[110] = NULL;
	_snekkja_producers_id[111] = NULL;
	_snekkja_producers_id[112] = NULL;
	_snekkja_producers_id[113] = NULL;
	_snekkja_producers_id[114] = NULL;
	_snekkja_producers_id[115] = NULL;
	_snekkja_producers_id[116] = NULL;
	_snekkja_producers_id[117] = NULL;
	_snekkja_producers_id[118] = NULL;
	_snekkja_producers_id[119] = NULL;
	_snekkja_producers_id[120] = NULL;
	_snekkja_producers_id[121] = NULL;
	_snekkja_producers_id[122] = NULL;
	_snekkja_producers_id[123] = NULL;
	_snekkja_producers_id[124] = NULL;
	_snekkja_producers_id[125] = NULL;
	_snekkja_producers_id[126] = NULL;
	_snekkja_producers_id[127] = NULL;

	_snekkja_consumers_id = malloc(sizeof(size_t*) * _snekkja_n);
	_snekkja_consumers_id[0] = NULL;
	_snekkja_consumers_id[1] = NULL;
	_snekkja_consumers_id[2] = NULL;
	_snekkja_consumers_id[3] = NULL;
	_snekkja_consumers_id[4] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[4][0] = 3;
	_snekkja_consumers_id[5] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[5][0] = 3;
	_snekkja_consumers_id[6] = NULL;
	_snekkja_consumers_id[7] = NULL;
	_snekkja_consumers_id[8] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[8][0] = 4;
	_snekkja_consumers_id[9] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[9][0] = 4;
	_snekkja_consumers_id[10] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[10][0] = 5;
	_snekkja_consumers_id[11] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[11][0] = 5;
	_snekkja_consumers_id[12] = NULL;
	_snekkja_consumers_id[13] = NULL;
	_snekkja_consumers_id[14] = NULL;
	_snekkja_consumers_id[15] = NULL;
	_snekkja_consumers_id[16] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[16][0] = 8;
	_snekkja_consumers_id[17] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[17][0] = 8;
	_snekkja_consumers_id[18] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[18][0] = 9;
	_snekkja_consumers_id[19] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[19][0] = 9;
	_snekkja_consumers_id[20] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[20][0] = 10;
	_snekkja_consumers_id[21] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[21][0] = 10;
	_snekkja_consumers_id[22] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[22][0] = 11;
	_snekkja_consumers_id[23] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[23][0] = 11;
	_snekkja_consumers_id[24] = NULL;
	_snekkja_consumers_id[25] = NULL;
	_snekkja_consumers_id[26] = NULL;
	_snekkja_consumers_id[27] = NULL;
	_snekkja_consumers_id[28] = NULL;
	_snekkja_consumers_id[29] = NULL;
	_snekkja_consumers_id[30] = NULL;
	_snekkja_consumers_id[31] = NULL;
	_snekkja_consumers_id[32] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[32][0] = 16;
	_snekkja_consumers_id[33] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[33][0] = 16;
	_snekkja_consumers_id[34] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[34][0] = 17;
	_snekkja_consumers_id[35] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[35][0] = 17;
	_snekkja_consumers_id[36] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[36][0] = 18;
	_snekkja_consumers_id[37] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[37][0] = 18;
	_snekkja_consumers_id[38] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[38][0] = 19;
	_snekkja_consumers_id[39] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[39][0] = 19;
	_snekkja_consumers_id[40] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[40][0] = 20;
	_snekkja_consumers_id[41] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[41][0] = 20;
	_snekkja_consumers_id[42] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[42][0] = 21;
	_snekkja_consumers_id[43] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[43][0] = 21;
	_snekkja_consumers_id[44] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[44][0] = 22;
	_snekkja_consumers_id[45] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[45][0] = 22;
	_snekkja_consumers_id[46] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[46][0] = 23;
	_snekkja_consumers_id[47] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[47][0] = 23;
	_snekkja_consumers_id[48] = NULL;
	_snekkja_consumers_id[49] = NULL;
	_snekkja_consumers_id[50] = NULL;
	_snekkja_consumers_id[51] = NULL;
	_snekkja_consumers_id[52] = NULL;
	_snekkja_consumers_id[53] = NULL;
	_snekkja_consumers_id[54] = NULL;
	_snekkja_consumers_id[55] = NULL;
	_snekkja_consumers_id[56] = NULL;
	_snekkja_consumers_id[57] = NULL;
	_snekkja_consumers_id[58] = NULL;
	_snekkja_consumers_id[59] = NULL;
	_snekkja_consumers_id[60] = NULL;
	_snekkja_consumers_id[61] = NULL;
	_snekkja_consumers_id[62] = NULL;
	_snekkja_consumers_id[63] = NULL;
	_snekkja_consumers_id[64] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[64][0] = 32;
	_snekkja_consumers_id[65] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[65][0] = 32;
	_snekkja_consumers_id[66] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[66][0] = 33;
	_snekkja_consumers_id[67] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[67][0] = 33;
	_snekkja_consumers_id[68] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[68][0] = 34;
	_snekkja_consumers_id[69] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[69][0] = 34;
	_snekkja_consumers_id[70] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[70][0] = 35;
	_snekkja_consumers_id[71] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[71][0] = 35;
	_snekkja_consumers_id[72] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[72][0] = 36;
	_snekkja_consumers_id[73] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[73][0] = 36;
	_snekkja_consumers_id[74] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[74][0] = 37;
	_snekkja_consumers_id[75] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[75][0] = 37;
	_snekkja_consumers_id[76] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[76][0] = 38;
	_snekkja_consumers_id[77] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[77][0] = 38;
	_snekkja_consumers_id[78] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[78][0] = 39;
	_snekkja_consumers_id[79] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[79][0] = 39;
	_snekkja_consumers_id[80] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[80][0] = 40;
	_snekkja_consumers_id[81] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[81][0] = 40;
	_snekkja_consumers_id[82] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[82][0] = 41;
	_snekkja_consumers_id[83] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[83][0] = 41;
	_snekkja_consumers_id[84] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[84][0] = 42;
	_snekkja_consumers_id[85] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[85][0] = 42;
	_snekkja_consumers_id[86] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[86][0] = 43;
	_snekkja_consumers_id[87] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[87][0] = 43;
	_snekkja_consumers_id[88] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[88][0] = 44;
	_snekkja_consumers_id[89] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[89][0] = 44;
	_snekkja_consumers_id[90] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[90][0] = 45;
	_snekkja_consumers_id[91] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[91][0] = 45;
	_snekkja_consumers_id[92] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[92][0] = 46;
	_snekkja_consumers_id[93] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[93][0] = 46;
	_snekkja_consumers_id[94] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[94][0] = 47;
	_snekkja_consumers_id[95] = malloc(sizeof(size_t) * 1);
	_snekkja_consumers_id[95][0] = 47;
	_snekkja_consumers_id[96] = NULL;
	_snekkja_consumers_id[97] = NULL;
	_snekkja_consumers_id[98] = NULL;
	_snekkja_consumers_id[99] = NULL;
	_snekkja_consumers_id[100] = NULL;
	_snekkja_consumers_id[101] = NULL;
	_snekkja_consumers_id[102] = NULL;
	_snekkja_consumers_id[103] = NULL;
	_snekkja_consumers_id[104] = NULL;
	_snekkja_consumers_id[105] = NULL;
	_snekkja_consumers_id[106] = NULL;
	_snekkja_consumers_id[107] = NULL;
	_snekkja_consumers_id[108] = NULL;
	_snekkja_consumers_id[109] = NULL;
	_snekkja_consumers_id[110] = NULL;
	_snekkja_consumers_id[111] = NULL;
	_snekkja_consumers_id[112] = NULL;
	_snekkja_consumers_id[113] = NULL;
	_snekkja_consumers_id[114] = NULL;
	_snekkja_consumers_id[115] = NULL;
	_snekkja_consumers_id[116] = NULL;
	_snekkja_consumers_id[117] = NULL;
	_snekkja_consumers_id[118] = NULL;
	_snekkja_consumers_id[119] = NULL;
	_snekkja_consumers_id[120] = NULL;
	_snekkja_consumers_id[121] = NULL;
	_snekkja_consumers_id[122] = NULL;
	_snekkja_consumers_id[123] = NULL;
	_snekkja_consumers_id[124] = NULL;
	_snekkja_consumers_id[125] = NULL;
	_snekkja_consumers_id[126] = NULL;
	_snekkja_consumers_id[127] = NULL;

	_snekkja_schedule = malloc(sizeof(snekkja_schedule_task_t*) * _snekkja_p);
	_snekkja_schedule[0] = malloc(sizeof(snekkja_schedule_task_t) * 1);
	_snekkja_schedule[0][0].id = 3;
	_snekkja_schedule[0][0].start_time = 0;
	_snekkja_schedule[0][0].frequency = 533;
	_snekkja_schedule[1] = malloc(sizeof(snekkja_schedule_task_t) * 2);
	_snekkja_schedule[1][0].id = 5;
	_snekkja_schedule[1][0].start_time = 0;
	_snekkja_schedule[1][0].frequency = 533;
	_snekkja_schedule[1][1].id = 6;
	_snekkja_schedule[1][1].start_time = 1;
	_snekkja_schedule[1][1].frequency = 533;
	_snekkja_schedule[2] = malloc(sizeof(snekkja_schedule_task_t) * 4);
	_snekkja_schedule[2][0].id = 9;
	_snekkja_schedule[2][0].start_time = 0;
	_snekkja_schedule[2][0].frequency = 533;
	_snekkja_schedule[2][1].id = 10;
	_snekkja_schedule[2][1].start_time = 1;
	_snekkja_schedule[2][1].frequency = 533;
	_snekkja_schedule[2][2].id = 11;
	_snekkja_schedule[2][2].start_time = 2;
	_snekkja_schedule[2][2].frequency = 533;
	_snekkja_schedule[2][3].id = 12;
	_snekkja_schedule[2][3].start_time = 3;
	_snekkja_schedule[2][3].frequency = 533;
	_snekkja_schedule[3] = malloc(sizeof(snekkja_schedule_task_t) * 8);
	_snekkja_schedule[3][0].id = 17;
	_snekkja_schedule[3][0].start_time = 0;
	_snekkja_schedule[3][0].frequency = 533;
	_snekkja_schedule[3][1].id = 18;
	_snekkja_schedule[3][1].start_time = 1;
	_snekkja_schedule[3][1].frequency = 533;
	_snekkja_schedule[3][2].id = 19;
	_snekkja_schedule[3][2].start_time = 2;
	_snekkja_schedule[3][2].frequency = 533;
	_snekkja_schedule[3][3].id = 20;
	_snekkja_schedule[3][3].start_time = 3;
	_snekkja_schedule[3][3].frequency = 533;
	_snekkja_schedule[3][4].id = 21;
	_snekkja_schedule[3][4].start_time = 4;
	_snekkja_schedule[3][4].frequency = 533;
	_snekkja_schedule[3][5].id = 22;
	_snekkja_schedule[3][5].start_time = 5;
	_snekkja_schedule[3][5].frequency = 533;
	_snekkja_schedule[3][6].id = 23;
	_snekkja_schedule[3][6].start_time = 6;
	_snekkja_schedule[3][6].frequency = 533;
	_snekkja_schedule[3][7].id = 24;
	_snekkja_schedule[3][7].start_time = 7;
	_snekkja_schedule[3][7].frequency = 533;
	_snekkja_schedule[4] = malloc(sizeof(snekkja_schedule_task_t) * 16);
	_snekkja_schedule[4][0].id = 33;
	_snekkja_schedule[4][0].start_time = 0;
	_snekkja_schedule[4][0].frequency = 533;
	_snekkja_schedule[4][1].id = 34;
	_snekkja_schedule[4][1].start_time = 1;
	_snekkja_schedule[4][1].frequency = 533;
	_snekkja_schedule[4][2].id = 35;
	_snekkja_schedule[4][2].start_time = 2;
	_snekkja_schedule[4][2].frequency = 533;
	_snekkja_schedule[4][3].id = 36;
	_snekkja_schedule[4][3].start_time = 3;
	_snekkja_schedule[4][3].frequency = 533;
	_snekkja_schedule[4][4].id = 37;
	_snekkja_schedule[4][4].start_time = 4;
	_snekkja_schedule[4][4].frequency = 533;
	_snekkja_schedule[4][5].id = 38;
	_snekkja_schedule[4][5].start_time = 5;
	_snekkja_schedule[4][5].frequency = 533;
	_snekkja_schedule[4][6].id = 39;
	_snekkja_schedule[4][6].start_time = 6;
	_snekkja_schedule[4][6].frequency = 533;
	_snekkja_schedule[4][7].id = 40;
	_snekkja_schedule[4][7].start_time = 7;
	_snekkja_schedule[4][7].frequency = 533;
	_snekkja_schedule[4][8].id = 41;
	_snekkja_schedule[4][8].start_time = 8;
	_snekkja_schedule[4][8].frequency = 533;
	_snekkja_schedule[4][9].id = 42;
	_snekkja_schedule[4][9].start_time = 9;
	_snekkja_schedule[4][9].frequency = 533;
	_snekkja_schedule[4][10].id = 43;
	_snekkja_schedule[4][10].start_time = 10;
	_snekkja_schedule[4][10].frequency = 533;
	_snekkja_schedule[4][11].id = 44;
	_snekkja_schedule[4][11].start_time = 11;
	_snekkja_schedule[4][11].frequency = 533;
	_snekkja_schedule[4][12].id = 45;
	_snekkja_schedule[4][12].start_time = 12;
	_snekkja_schedule[4][12].frequency = 533;
	_snekkja_schedule[4][13].id = 46;
	_snekkja_schedule[4][13].start_time = 13;
	_snekkja_schedule[4][13].frequency = 533;
	_snekkja_schedule[4][14].id = 47;
	_snekkja_schedule[4][14].start_time = 14;
	_snekkja_schedule[4][14].frequency = 533;
	_snekkja_schedule[4][15].id = 48;
	_snekkja_schedule[4][15].start_time = 15;
	_snekkja_schedule[4][15].frequency = 533;
	_snekkja_schedule[5] = malloc(sizeof(snekkja_schedule_task_t) * 32);
	_snekkja_schedule[5][0].id = 65;
	_snekkja_schedule[5][0].start_time = 0;
	_snekkja_schedule[5][0].frequency = 533;
	_snekkja_schedule[5][1].id = 66;
	_snekkja_schedule[5][1].start_time = 1;
	_snekkja_schedule[5][1].frequency = 533;
	_snekkja_schedule[5][2].id = 67;
	_snekkja_schedule[5][2].start_time = 2;
	_snekkja_schedule[5][2].frequency = 533;
	_snekkja_schedule[5][3].id = 68;
	_snekkja_schedule[5][3].start_time = 3;
	_snekkja_schedule[5][3].frequency = 533;
	_snekkja_schedule[5][4].id = 69;
	_snekkja_schedule[5][4].start_time = 4;
	_snekkja_schedule[5][4].frequency = 533;
	_snekkja_schedule[5][5].id = 70;
	_snekkja_schedule[5][5].start_time = 5;
	_snekkja_schedule[5][5].frequency = 533;
	_snekkja_schedule[5][6].id = 71;
	_snekkja_schedule[5][6].start_time = 6;
	_snekkja_schedule[5][6].frequency = 533;
	_snekkja_schedule[5][7].id = 72;
	_snekkja_schedule[5][7].start_time = 7;
	_snekkja_schedule[5][7].frequency = 533;
	_snekkja_schedule[5][8].id = 73;
	_snekkja_schedule[5][8].start_time = 8;
	_snekkja_schedule[5][8].frequency = 533;
	_snekkja_schedule[5][9].id = 74;
	_snekkja_schedule[5][9].start_time = 9;
	_snekkja_schedule[5][9].frequency = 533;
	_snekkja_schedule[5][10].id = 75;
	_snekkja_schedule[5][10].start_time = 10;
	_snekkja_schedule[5][10].frequency = 533;
	_snekkja_schedule[5][11].id = 76;
	_snekkja_schedule[5][11].start_time = 11;
	_snekkja_schedule[5][11].frequency = 533;
	_snekkja_schedule[5][12].id = 77;
	_snekkja_schedule[5][12].start_time = 12;
	_snekkja_schedule[5][12].frequency = 533;
	_snekkja_schedule[5][13].id = 78;
	_snekkja_schedule[5][13].start_time = 13;
	_snekkja_schedule[5][13].frequency = 533;
	_snekkja_schedule[5][14].id = 79;
	_snekkja_schedule[5][14].start_time = 14;
	_snekkja_schedule[5][14].frequency = 533;
	_snekkja_schedule[5][15].id = 80;
	_snekkja_schedule[5][15].start_time = 15;
	_snekkja_schedule[5][15].frequency = 533;
	_snekkja_schedule[5][16].id = 81;
	_snekkja_schedule[5][16].start_time = 16;
	_snekkja_schedule[5][16].frequency = 533;
	_snekkja_schedule[5][17].id = 82;
	_snekkja_schedule[5][17].start_time = 17;
	_snekkja_schedule[5][17].frequency = 533;
	_snekkja_schedule[5][18].id = 83;
	_snekkja_schedule[5][18].start_time = 18;
	_snekkja_schedule[5][18].frequency = 533;
	_snekkja_schedule[5][19].id = 84;
	_snekkja_schedule[5][19].start_time = 19;
	_snekkja_schedule[5][19].frequency = 533;
	_snekkja_schedule[5][20].id = 85;
	_snekkja_schedule[5][20].start_time = 20;
	_snekkja_schedule[5][20].frequency = 533;
	_snekkja_schedule[5][21].id = 86;
	_snekkja_schedule[5][21].start_time = 21;
	_snekkja_schedule[5][21].frequency = 533;
	_snekkja_schedule[5][22].id = 87;
	_snekkja_schedule[5][22].start_time = 22;
	_snekkja_schedule[5][22].frequency = 533;
	_snekkja_schedule[5][23].id = 88;
	_snekkja_schedule[5][23].start_time = 23;
	_snekkja_schedule[5][23].frequency = 533;
	_snekkja_schedule[5][24].id = 89;
	_snekkja_schedule[5][24].start_time = 24;
	_snekkja_schedule[5][24].frequency = 533;
	_snekkja_schedule[5][25].id = 90;
	_snekkja_schedule[5][25].start_time = 25;
	_snekkja_schedule[5][25].frequency = 533;
	_snekkja_schedule[5][26].id = 91;
	_snekkja_schedule[5][26].start_time = 26;
	_snekkja_schedule[5][26].frequency = 533;
	_snekkja_schedule[5][27].id = 92;
	_snekkja_schedule[5][27].start_time = 27;
	_snekkja_schedule[5][27].frequency = 533;
	_snekkja_schedule[5][28].id = 93;
	_snekkja_schedule[5][28].start_time = 28;
	_snekkja_schedule[5][28].frequency = 533;
	_snekkja_schedule[5][29].id = 94;
	_snekkja_schedule[5][29].start_time = 29;
	_snekkja_schedule[5][29].frequency = 533;
	_snekkja_schedule[5][30].id = 95;
	_snekkja_schedule[5][30].start_time = 30;
	_snekkja_schedule[5][30].frequency = 533;
	_snekkja_schedule[5][31].id = 96;
	_snekkja_schedule[5][31].start_time = 31;
	_snekkja_schedule[5][31].frequency = 533;
}

void snekkja_schedule_destroy()
{
	free(_snekkja_schedule[5]);
	free(_snekkja_schedule[4]);
	free(_snekkja_schedule[3]);
	free(_snekkja_schedule[2]);
	free(_snekkja_schedule[1]);
	free(_snekkja_schedule[0]);
	free(_snekkja_schedule);
	free(_snekkja_consumers_id[95]);
	free(_snekkja_consumers_id[94]);
	free(_snekkja_consumers_id[93]);
	free(_snekkja_consumers_id[92]);
	free(_snekkja_consumers_id[91]);
	free(_snekkja_consumers_id[90]);
	free(_snekkja_consumers_id[89]);
	free(_snekkja_consumers_id[88]);
	free(_snekkja_consumers_id[87]);
	free(_snekkja_consumers_id[86]);
	free(_snekkja_consumers_id[85]);
	free(_snekkja_consumers_id[84]);
	free(_snekkja_consumers_id[83]);
	free(_snekkja_consumers_id[82]);
	free(_snekkja_consumers_id[81]);
	free(_snekkja_consumers_id[80]);
	free(_snekkja_consumers_id[79]);
	free(_snekkja_consumers_id[78]);
	free(_snekkja_consumers_id[77]);
	free(_snekkja_consumers_id[76]);
	free(_snekkja_consumers_id[75]);
	free(_snekkja_consumers_id[74]);
	free(_snekkja_consumers_id[73]);
	free(_snekkja_consumers_id[72]);
	free(_snekkja_consumers_id[71]);
	free(_snekkja_consumers_id[70]);
	free(_snekkja_consumers_id[69]);
	free(_snekkja_consumers_id[68]);
	free(_snekkja_consumers_id[67]);
	free(_snekkja_consumers_id[66]);
	free(_snekkja_consumers_id[65]);
	free(_snekkja_consumers_id[64]);
	free(_snekkja_consumers_id[47]);
	free(_snekkja_consumers_id[46]);
	free(_snekkja_consumers_id[45]);
	free(_snekkja_consumers_id[44]);
	free(_snekkja_consumers_id[43]);
	free(_snekkja_consumers_id[42]);
	free(_snekkja_consumers_id[41]);
	free(_snekkja_consumers_id[40]);
	free(_snekkja_consumers_id[39]);
	free(_snekkja_consumers_id[38]);
	free(_snekkja_consumers_id[37]);
	free(_snekkja_consumers_id[36]);
	free(_snekkja_consumers_id[35]);
	free(_snekkja_consumers_id[34]);
	free(_snekkja_consumers_id[33]);
	free(_snekkja_consumers_id[32]);
	free(_snekkja_consumers_id[23]);
	free(_snekkja_consumers_id[22]);
	free(_snekkja_consumers_id[21]);
	free(_snekkja_consumers_id[20]);
	free(_snekkja_consumers_id[19]);
	free(_snekkja_consumers_id[18]);
	free(_snekkja_consumers_id[17]);
	free(_snekkja_consumers_id[16]);
	free(_snekkja_consumers_id[11]);
	free(_snekkja_consumers_id[10]);
	free(_snekkja_consumers_id[9]);
	free(_snekkja_consumers_id[8]);
	free(_snekkja_consumers_id[5]);
	free(_snekkja_consumers_id[4]);
	free(_snekkja_consumers_id);
	free(_snekkja_producers_id[47]);
	free(_snekkja_producers_id[46]);
	free(_snekkja_producers_id[45]);
	free(_snekkja_producers_id[44]);
	free(_snekkja_producers_id[43]);
	free(_snekkja_producers_id[42]);
	free(_snekkja_producers_id[41]);
	free(_snekkja_producers_id[40]);
	free(_snekkja_producers_id[39]);
	free(_snekkja_producers_id[38]);
	free(_snekkja_producers_id[37]);
	free(_snekkja_producers_id[36]);
	free(_snekkja_producers_id[35]);
	free(_snekkja_producers_id[34]);
	free(_snekkja_producers_id[33]);
	free(_snekkja_producers_id[32]);
	free(_snekkja_producers_id[23]);
	free(_snekkja_producers_id[22]);
	free(_snekkja_producers_id[21]);
	free(_snekkja_producers_id[20]);
	free(_snekkja_producers_id[19]);
	free(_snekkja_producers_id[18]);
	free(_snekkja_producers_id[17]);
	free(_snekkja_producers_id[16]);
	free(_snekkja_producers_id[11]);
	free(_snekkja_producers_id[10]);
	free(_snekkja_producers_id[9]);
	free(_snekkja_producers_id[8]);
	free(_snekkja_producers_id[5]);
	free(_snekkja_producers_id[4]);
	free(_snekkja_producers_id[2]);
	free(_snekkja_producers_id);
	free(_snekkja_remote_producers_in_task);
	free(_snekkja_remote_consumers_in_task);
	free(_snekkja_producers_in_task);
	free(_snekkja_consumers_in_task);
	free(_snekkja_producers_in_core);
	free(_snekkja_consumers_in_core);
	free(_snekkja_tasks_in_core);
}

void*
snekkja_function(size_t id, task_status_t status)
{
	switch(id)
	{
		default:
		case 1:
			switch(status)
			{
				case TASK_INVALID:
					return 0;
				break;
				case TASK_INIT:
					return (void*)&snekkja_init(merge, 1);
				break;
				case TASK_START:
					return (void*)&snekkja_start(merge, 1);
				break;
				case TASK_CHECK:
					return 0;
				break;
				case TASK_WORK:
					return 0;
				break;
				case TASK_PUSH:
					return 0;
				break;
				case TASK_RUN:
					return (void*)&snekkja_run(merge, 1);
				break;
				case TASK_KILLED:
					return (void*)&snekkja_destroy(merge, 1);
				break;
				case TASK_ZOMBIE:
					return 0;
				break;
				default:
					return 0;
				break;
			}
		break;
	}

	return 0;
}
